[package]
name = "buttons"
version = "0.1.0"
edition = "2021"

[dependencies]
button-driver = { version = "0.2.2", features = ["std", "embedded_hal"] }
embedded-hal = "1.0.0"
esp-idf-svc = { version = "0.51", features = [
    "critical-section",
    "embassy-time-driver",
    "embassy-sync",
] }
