[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-idf-svc = "0.51"
heapless = "0.8"
serde_json = "1.0.143"
log = "0.4"
anyhow = "1.0" # New Dependency
embedded-svc = "0.28.1"
base64 = "0.22.1"
esp-idf-sys = "0.36.1"