[package]
name = "sensors"
version = "0.1.0"
edition = "2021"

[dependencies]
hdc1080 = { path = "../hdc1080" }
embedded-hal = "1.0.0"
log = "0.4"
esp-idf-svc = { version = "0.51", features = [
    "critical-section",
    "embassy-time-driver",
    "embassy-sync",
] }
